### ISSUE TITLE
Consideration of Deepseek V3 as the new default model

### ISSUE THREAD

**Issue by ai-christianson** [ai-christianson/RA.Aid#13]
The new Deepseek V3 model is performing better than sonnet on the aider polyglot benchmark: https://aider.chat/docs/leaderboards/.

O1 is currently performing at the top, but is quite expensive to run. It makes a good expert model, though.

Assuming Deepseek V3 is similar in cost or lower than sonnet and performs better, I think it is worth considering it as a new default. 

I haven't had a chance to test it yet, but it seems worth exploring.

**Comment by ai-christianson** [comment]
I'm getting multiple repeated function calls when using Deepseek V3, which I wasn't getting when using claude.

![image](https://github.com/user-attachments/assets/1ec4c474-536c-44d2-9ff9-bed9af70622f)

This is working directly against their API using:

```
export OPENAI_API_BASE=https://api.deepseek.com
ra-aid --provider openai-compatible --model deepseek-chat --chat
```

Since they're still rolling out v3, it is possible my API calls are not hitting the latest model. Will try to verify that.

**Comment by ai-christianson** [comment]
![image](https://github.com/user-attachments/assets/d46fe286-5996-469e-a684-477ae3d3afdd)

Deepseek docs say they're fully upgraded to v3. So unless we can fix the behavior, Deepseek V3 is likely not a good fit for being a default agent model, but it might be a good model for the aider programming task itself.

The other issue is limited context length (64K with 8K output tokens). This low of a limit would likely end up being a major issue for processes that use many agent steps.

**Comment by tdobson** [comment]
I have interest here. Can we use Deepseek v3 for programming, and sonnet 3.5 for the agent part?

**Comment by ai-christianson** [comment]
Yeah I think with careful use of AIDER_FLAGS it would be possible to use Deepseek for aider and sonnet for RA.Aid.

I'd be open to a new feature request to better support configuration of the aider model independently.

Note that RA.Aid will work with Deepseek v3 for the agent, just not as well as claude.
