### ISSUE TITLE
Proposal: Allow Setting Default Provider and Model via Environment Variables

### ISSUE THREAD

**Issue by zzt108** [ai-christianson/RA.Aid#18]
Description:

Currently, RA.Aid defaults to using Anthropic's Claude models, requiring users to specify the --provider and --model flags every time they want to use a different provider like OpenAI or OpenRouter. This can be cumbersome for users who primarily rely on alternative providers.

This issue proposes a way to improve user experience by allowing the configuration of a default provider and model through environment variables.

Problem:

RA.Aid always defaults to Anthropic, even if users have other providers' API keys set up (e.g., OPENAI_API_KEY, OPENROUTER_API_KEY).

The validate_environment function in env.py prioritizes checking for ANTHROPIC_API_KEY and raises an error if it's not found, regardless of whether the user intends to use Anthropic or not.

Users who prefer other providers must specify --provider and --model in every command, which is inconvenient.

Proposed Solution:

Introduce two new environment variables:

RA_AID_DEFAULT_PROVIDER: Specifies the desired default provider (e.g., openai, openrouter).

RA_AID_DEFAULT_MODEL: Specifies the desired default model for the chosen provider.

Modify the parse_arguments() function in __main__.py to:

Read the values of RA_AID_DEFAULT_PROVIDER and RA_AID_DEFAULT_MODEL from the environment.

Use these values as defaults for the --provider and --model arguments, respectively, if these arguments are not provided by the user on the command line.

Example Code Modification (in __main__.py):

def parse_arguments():
    # ... other code ...
    parser.add_argument(
        '--provider',
        type=str,
        default=os.environ.get('RA_AID_DEFAULT_PROVIDER', 'anthropic'),  # Read from env, fallback to 'anthropic'
        choices=['anthropic', 'openai', 'openrouter', 'openai-compatible'],
        help='The LLM provider to use'
    )
    parser.add_argument(
        '--model',
        type=str,
        default=os.environ.get('RA_AID_DEFAULT_MODEL'),  # Read from env, no default here
        help='The model name to use (If not set, provider-specific default will be used)'
    )
    # ... rest of the code ...
Use code [with caution](https://support.google.com/legal/answer/13505487).
Python
Also, the check for the ANTHROPIC_API_KEY in validate_environment function should happen only if no other provider is specified, neither via environment variables or command-line arguments.

Benefits:

Improved User Experience: Users can set their preferred provider and model once and avoid repetitive typing.

Flexibility: Still allows overriding the defaults using command-line flags when needed.

Consistency: Makes RA.Aid behave more consistently with how users might expect environment variables to work.

Example Usage (after proposed changes):

User sets the following environment variables:

export RA_AID_DEFAULT_PROVIDER=openrouter
export RA_AID_DEFAULT_MODEL=mistralai/mistral-large-2402
Use code [with caution](https://support.google.com/legal/answer/13505487).
Bash
Now, they can run:

ra-aid -m "What is the capital of France?"
Use code with caution.
Bash
And RA.Aid will automatically use OpenRouter and the mistralai/mistral-large-2402 model without requiring the user to specify them explicitly.

Alternatives Considered:

Configuration File: A configuration file (e.g., YAML or JSON) could also be used, but environment variables are a more common and often simpler way to handle this type of setting.

Shell Aliases/Functions: While these are viable workarounds, they are specific to the user's shell environment and don't provide a system-wide solution.

I believe this enhancement would make RA.Aid more user-friendly and adaptable to different user preferences. I encourage the maintainers to consider this proposal and welcome any feedback or suggestions.

**Comment by ai-christianson** [comment]
Yeah we definitely need this, otherwise the flag lists will get unwieldy.

I suspect we probably will need file-based configuration, since there are multiple parameters per model, multiple models for multiple purposes, search API integration, etc.

The high-level design intent is to have sane defaults which can be overriden. RA.Aid is meant to get production-level work done, and as such needs to be configurable and flexible for power users, and especially those who want to use open models.

## Temporary Workaround

If you're in bash/zsh or similar, for now, use `ctrl-r` for command history search so you don't have to type or paste it, or use `alias`.
