### ISSUE TITLE
If Anthropic key is not set in environment an error is raised even if another provider/model is specified

### ISSUE THREAD

**Issue by zzt108** [ai-christianson/RA.Aid#19]
1. validate_environment Function:

The validate_environment function in env.py is designed to check for the presence of necessary API keys before the command-line arguments are fully processed.

It starts with the assumption that you might be using Anthropic because it checks for the ANTHROPIC_API_KEY first.

if provider in PROVIDER_CONFIGS:
    config = PROVIDER_CONFIGS[provider]
    if config.base_required and not os.environ.get(config.key_name):
        missing.append(f'{config.key_name} environment variable is not set')

Python
In this code, if provider is set to anthropic and ANTHROPIC_API_KEY is not found, it will add the error message to the missing list.

The code does not take into consideration the values of --provider and --model specified on the command line at this stage. It's only checking environment variables based on a hardcoded priority (Anthropic first).

Later in the function, it checks if there are any missing keys and, if so, exits with an error:

if missing:
    print_error("Missing required dependencies:")
    for item in missing:
        print_error(f"- {item}")
    sys.exit(1)

Python
2. Order of Operations:

The core issue is the order in which things happen:

Environment variable validation (validate_environment) happens before full command-line argument parsing.

The default provider is assumed to be Anthropic unless modified later by command-line arguments.

3. Impact:

Even if I provide --provider openai or --provider openrouter on the command line, the validate_environment function will still check for ANTHROPIC_API_KEY first and raise an error if it's not found.

In essence, the current code has an implicit dependency on the ANTHROPIC_API_KEY being set, even when you intend to use another provider.

Proposed Solutions (as mentioned in the issue draft):

Prioritize Command-line Arguments: Modify validate_environment to respect the --provider flag first, if it's provided. Only check for ANTHROPIC_API_KEY if --provider is not set or is explicitly set to anthropic.

Environment Variable Defaults: Implement the RA_AID_DEFAULT_PROVIDER and RA_AID_DEFAULT_MODEL environment variables as I described earlier. This would change the default behavior and only require ANTHROPIC_API_KEY if the user doesn't set defaults and doesn't use the --provider flag.

**Comment by ai-christianson** [comment]
Which version/commit is this?

**Comment by zzt108** [comment]
ra-aid                    0.10.1

I installed this morning with PIP

**Comment by ai-christianson** [comment]
Testing this out locally:

```
(ratest-2024-12-17) ~/tmp/ratest-2024-12-17 $ printenv | cut -d= -f1 | grep API_KEY
OPENAI_API_KEY
(ratest-2024-12-17) ~/tmp/ratest-2024-12-17 $ ra-aid --version                     
ra-aid 0.10.1
(ratest-2024-12-17) ~/tmp/ratest-2024-12-17 $ ra-aid --provider openai --model gpt-4o --chat
╭─────────────────────────────────────────────────────────────────────────── Web Research Disabled ────────────────────────────────────────────────────────────────────────────╮
│ Web research disabled due to missing configuration:                                                                                                                          │
│ - TAVILY_API_KEY environment variable is not set                                                                                                                             │
│ Set the required environment variables to enable web research.                                                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│🚀 Chat Mode                                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────── 💭 Question for Human ────────────────────────────────────────────────────────────────────────────╮
│ What would you like help with?                                                                                                                                               │
│                                                                                                                                                                              │
│ Multiline input is supported; use Ctrl+D to submit. Use Ctrl+C to exit the program.                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

>                                                                                                                                                                               

 👋 Bye!

(ratest-2024-12-17) ~/tmp/ratest-2024-12-17 $ ra-aid --provider openai --model gpt-4o -m 'write a hello world in c++'
╭─────────────────────────────────────────────────────────────────────────── Web Research Disabled ────────────────────────────────────────────────────────────────────────────╮
│ Web research disabled due to missing configuration:                                                                                                                          │
│ - TAVILY_API_KEY environment variable is not set                                                                                                                             │
│ Set the required environment variables to enable web research.                                                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│🔎 Research Stage                                                                                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭───────────────────────────────────────────────────────────────────────────── ✅ Task Completed ──────────────────────────────────────────────────────────────────────────────╮
│ Here's a simple "Hello, World!" program in C++:                                                                                                                              │
│                                                                                                                                                                              │
│                                                                                                                                                                              │
│  #include <iostream>                                                                                                                                                         │
│                                                                                                                                                                              │
│  int main() {                                                                                                                                                                │
│      std::cout << "Hello, World!" << std::endl;                                                                                                                              │
│      return 0;                                                                                                                                                               │
│  }                                                                                                                                                                           │
│                                                                                                                                                                              │
│                                                                                                                                                                              │
│ This program includes the iostream library, which allows for input and output operations. The main function outputs "Hello, World!" to the console and returns 0 to indicate │
│ successful execution.                                                                                                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
^C2024-12-27 14:21:36,464 - ra_aid.ra_aid.agent_utils - ERROR - Research agent failed: Interrupt requested
Traceback (most recent call last):
  File "/home/user/tmp/ratest-2024-12-17/.venv/lib/python3.12/site-packages/ra_aid/agent_utils.py", line 167, in run_research_agent
    return run_agent_with_retry(agent, prompt, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tmp/ratest-2024-12-17/.venv/lib/python3.12/site-packages/ra_aid/agent_utils.py", line 472, in run_agent_with_retry
    check_interrupt()
  File "/home/user/tmp/ratest-2024-12-17/.venv/lib/python3.12/site-packages/ra_aid/agent_utils.py", line 447, in check_interrupt
    raise AgentInterrupt("Interrupt requested")
ra_aid.exceptions.AgentInterrupt: Interrupt requested

 👋 Bye!

```

Can you give it a try with the `--verbose` flag and paste the full log?

**Comment by zzt108** [comment]
I redeployed on my home PC with the exact same scripts I used yesterday on my work PC. It works now with 0.10.3

PS C:\Git\ra-aid> .\run-ra-aid.ps1
API Keys found: OPENAI_API_KEY OPENROUTER_API_KEY
ra-aid version: ra-aid 0.10.3
╭───────────────────────────────────────────────────────────────────────────────────────── Web Research Disabled ─────────────────────────────────────────────────────────────────────────────────────────╮
│ Web research disabled due to missing configuration:                                                                                                                                                     │
│ - TAVILY_API_KEY environment variable is not set                                                                                                                                                        │
│ Set the required environment variables to enable web research.                                                                                                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│🚀 Chat Mode                                                                                                                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭───────────────────────────────────────────────────────────────────────────────────────── 💭 Question for Human ─────────────────────────────────────────────────────────────────────────────────────────╮
│ What would you like help with?                                                                                                                                                                          │
│                                                                                                                                                                                                         │
│ Multiline input is supported; use Ctrl+D to submit. Use Ctrl+C to exit the program.                                                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

>

 👋 Bye!

PS C:\Git\ra-aid> ra-aid --provider openai --model gpt-4o -m 'write a hello world in c++'
╭───────────────────────────────────────────────────────────────────────────────────────── Web Research Disabled ─────────────────────────────────────────────────────────────────────────────────────────╮
│ Web research disabled due to missing configuration:                                                                                                                                                     │
│ - TAVILY_API_KEY environment variable is not set                                                                                                                                                        │
│ Set the required environment variables to enable web research.                                                                                                                                          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│🔎 Research Stage                                                                                                                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────── ✅ Task Completed ───────────────────────────────────────────────────────────────────────────────────────────╮
│ Here's a simple "Hello, World!" program in C++:                                                                                                                                                         │
│                                                                                                                                                                                                         │
│                                                                                                                                                                                                         │
│  #include <iostream>                                                                                                                                                                                    │
│                                                                                                                                                                                                         │
│  int main() {                                                                                                                                                                                           │
│      std::cout << "Hello, World!" << std::endl;                                                                                                                                                         │
│      return 0;                                                                                                                                                                                          │
│  }                                                                                                                                                                                                      │
│                                                                                                                                                                                                         │
│                                                                                                                                                                                                         │
│ This program includes the iostream library, which allows for input and output operations. The main function is the entry point of the program, and it uses std::cout to print "Hello, World!" to the    │
│ console. The std::endl is used to insert a newline character and flush the output buffer. Finally, the program returns 0, indicating successful execution.                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭───────────────────────────────────────────────────────────────────────────────────────────── 🤖 Assistant ──────────────────────────────────────────────────────────────────────────────────────────────╮
│ I've provided a simple "Hello, World!" program in C++.                                                                                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
PS C:\Git\ra-aid>

**Comment by ai-christianson** [comment]
Thanks for the contribution :+1:
