### ISSUE TITLE
typo in agent_utils.py -- function: run_agent_with_retry

### ISSUE THREAD

**Issue by codenprogressive** [ai-christianson/RA.Aid#24]
https://github.com/ai-christianson/RA.Aid/blob/d3a4684d6987c5fc1abb87262cdbda28bf8017b6/ra_aid/agent_utils.py#L544

It think it should be `_global_memory['task_completed']` and not `_global_memory['taskd_completed'] `

**Comment by ai-christianson** [comment]
Fixed.
