### ISSUE TITLE
Add support for Ollama

### ISSUE THREAD

**Issue by leonj1** [ai-christianson/RA.Aid#4]
This project is great, but I ran up my Claude bill during one session. Could Ollama support be added for local usage and keep costs down? A stretch goal could be to start with Ollama, but fall back to the current implementation when its unable to solve the problem.

**Comment by ai-christianson** [comment]
I hear you about running up the claude bill. It should already support any openai-compatible endpoints including ollama. You would have to set --provider to openai-compatible and set OPENAI_API_BASE in the environment.

In my testing, I haven't been able to get any agent other than claude to work well, however. I'm not sure if it has to do with langgraph create_react_agent having specialized prompts for claude or not.

My hope is that over the next year or so, open models will catch up and become much more capable of driving agents like this.

**Comment by leonj1** [comment]
I see. Yea. Local Ollama is struggling. Thanks!
